version: 0.0
os: linux
files:
  - source: /html
    destination: /var/www/html
permissions:
  - object: /var/www/html
    owner: apache
    group: apache
    type:
      - directory
  - object: /var/www/html
    owner: apache
    group: apache
    type:
      - file
hooks:
  BeforeInstall:
    - location: .scripts/install_apache.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: .scripts/start_apache.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: .scripts/stop_apache.sh
      timeout: 300
      runas: root
